# Project information
site_name: BBOT Docs
site_url: https://blacklanternsecurity.github.io/bbot/
site_author: TheTechromancer
site_description: >-
  OSINT automation for hackers
# Repository
repo_name: blacklanternsecurity/bbot
repo_url: https://github.com/blacklanternsecurity/bbot

# Page tree
nav:
  - Basics:
    - Getting Started: index.md
    - How it Works: how_it_works.md
    - Comparison to Other Tools: comparison.md
  - Scanning:
    - scanning/index.md
    - Events: scanning/events.md
    - Output: scanning/output.md
    - Advanced Usage: scanning/advanced.md
    - Configuration:
      - scanning/configuration/index.md
      - Global Options: scanning/configuration/global_options.md
      - Module Options: scanning/configuration/module_options.md
    - Modules Table: scanning/modules_table.md
  - Contribution: contribution.md

theme:
  name: material
  logo: bbot.png
  features:
    - content.code.copy
    - navigation.sections
    - navigation.expand
    - toc.integrate
  palette: 
  - scheme: slate
    primary: black
    accent: deep orange

plugins:
  - search
  - extra-sass

markdown_extensions:
  - codehilite:
      use_pygments: True
      noclasses: True
      pygments_style: github-dark
