name: tests
on: [push, pull_request]
jobs:
  pypi:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/auto-pypi-fix'
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Build package
        run: poetry build
      - name: Add Pypi test repo
        run: poetry config repositories.test-pypi.url https://test.pypi.org/legacy/
      - name: Publish package
        run: poetry publish -r test-pypi -u __token__ -p "${{ secrets.TEST_PYPI_API_TOKEN }}"
