name: tests
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    # needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/docker-publishing' || github.ref == 'refs/heads/stable')
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry build
          poetry self add "poetry-dynamic-versioning[plugin]"
      - name: Build Pypi package
        if: github.ref == 'refs/heads/stable'
        run: python -m build
      - name: Publish Pypi package
        if: github.ref == 'refs/heads/stable'
        uses: pypa/gh-action-pypi-publish@release/v1.5
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Get BBOT version
        id: version
        run: |
          echo "::set-output name=BBOT_VERSION::$(poetry version | cut -d' ' -f2)"
      - name: Publish to Docker Hub (dev)
        if: github.ref == 'refs/heads/docker-publishing'
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: blacklanternsecurity/bbot
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,dev,${{ steps.version.outputs.BBOT_VERSION }}"
      - name: Publish to Docker Hub (stable)
        if: github.ref == 'refs/heads/stable'
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: blacklanternsecurity/bbot
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "stable,${{ steps.version.outputs.BBOT_VERSION }}"
      - name: Docker Hub Description (dev)
        if: github.ref == 'refs/heads/docker-publishing'
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: blacklanternsecurity/bbot
